// Shared per-city and per-region representative photo maps.
// Each URL is that place's own Wikipedia/Wikimedia Commons page image, spot-checked to actually depict the named location.
// Used by CityHero.tsx (city detail hero), PlaceholderImage.tsx (city cards) and region pages.

export const REGION_IMAGES: Record<string, string> = {
  "karadeniz": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Safranbolu_traditional_houses.jpg/960px-Safranbolu_traditional_houses.jpg",
  "ege": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/%C4%B0zmir_Clock_Tower%2C_December_2018.jpg/960px-%C4%B0zmir_Clock_Tower%2C_December_2018.jpg",
  "akdeniz": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg/960px-Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg",
  "marmara": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Bosphorus_Bridge_%28235499411%29.jpeg/960px-Bosphorus_Bridge_%28235499411%29.jpeg",
  "ic-anadolu": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Cappadociasunrise.jpg/960px-Cappadociasunrise.jpg",
  "dogu-anadolu": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ho%C5%9Fap_Kalesi_%28Van%2C_T%C3%BCrkiye%29.JPG/960px-Ho%C5%9Fap_Kalesi_%28Van%2C_T%C3%BCrkiye%29.JPG",
  "guneydogu-anadolu": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Mount_Nemrut.jpg/1280px-Mount_Nemrut.jpg",
};

export const CITY_IMAGES: Record<string, string> = {
  alacati: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Ala%C3%A7at%C4%B1_windmills.jpg/960px-Ala%C3%A7at%C4%B1_windmills.jpg",
  ayvalik: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Cunda_Island_%28Ayval%C4%B1k%2C_Turkey%29.JPG/960px-Cunda_Island_%28Ayval%C4%B1k%2C_Turkey%29.JPG",
  kusadasi: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Kusadasi_G%C3%BCvercinada_Castle.jpg/960px-Kusadasi_G%C3%BCvercinada_Castle.jpg",
  marmaris: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Marmaris_marina_view.jpg/960px-Marmaris_marina_view.jpg",
  alanya: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Alanya_Castle_and_Red_Tower.jpg/960px-Alanya_Castle_and_Red_Tower.jpg",
  urgup: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/%C3%9Crg%C3%BCp_cave_houses.jpg/960px-%C3%9Crg%C3%BCp_cave_houses.jpg",
  goreme: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/G%C3%B6reme_Open_Air_Museum_Cave_Church.jpg/960px-G%C3%B6reme_Open_Air_Museum_Cave_Church.jpg",
  bozcaada: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Bozcaada_Castle_view.jpg/960px-Bozcaada_Castle_view.jpg",
  gokceada: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/G%C3%B6k%C3%A7eada_Derek%C3%B6y.jpg/960px-G%C3%B6k%C3%A7eada_Derek%C3%B6y.jpg",
  uzungol: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Uzung%C3%B6l_Trabzon.jpg/960px-Uzung%C3%B6l_Trabzon.jpg",
  adana: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Varda_Demiryolu_Koprusu.jpg/960px-Varda_Demiryolu_Koprusu.jpg",
  adiyaman: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/AdiyamanUhrturm.jpg/960px-AdiyamanUhrturm.jpg",
  afyonkarahisar: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Burgberg_Afyonkarahisar_02.jpg/960px-Burgberg_Afyonkarahisar_02.jpg",
  agri: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/A%C4%9Fr%C4%B1_Mountain_from_I%C4%9Fd%C4%B1r_plain.jpg/960px-A%C4%9Fr%C4%B1_Mountain_from_I%C4%9Fd%C4%B1r_plain.jpg",
  aksaray: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/I_Love_Aksaray_-_Aksaray_Meydan%C4%B1.jpg/960px-I_Love_Aksaray_-_Aksaray_Meydan%C4%B1.jpg",
  amasra: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Amasra%2C_Turkey%2C_Castle%2C_view_from_the_island.jpg/960px-Amasra%2C_Turkey%2C_Castle%2C_view_from_the_island.jpg",
  amasya: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Ye%C5%9Fil%C4%B1rmak2.jpg/960px-Ye%C5%9Fil%C4%B1rmak2.jpg",
  ankara: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Ankara_asv2021-10_img11_view_from_Atakule_mall.jpg/960px-Ankara_asv2021-10_img11_view_from_Atakule_mall.jpg",
  antalya: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg/960px-Falezlerden_Antalya_Konyaalt%C4%B1_Plaj%C4%B1na_do%C4%9Fru_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg",
  ardahan: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/MOLC05.jpg/960px-MOLC05.jpg",
  artvin: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/A%C3%87%C3%9C_%C5%9Eehir_Yerle%C5%9Fkesi.jpg/960px-A%C3%87%C3%9C_%C5%9Eehir_Yerle%C5%9Fkesi.jpg",
  aydin: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/MonumentAyd%C4%B1n_%283%29.JPG/960px-MonumentAyd%C4%B1n_%283%29.JPG",
  balikesir: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/%C5%9Eahinderesi_Canyon.jpg/960px-%C5%9Eahinderesi_Canyon.jpg",
  batman: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Hasankeyf_Castle.jpg/960px-Hasankeyf_Castle.jpg",
  bayburt: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Bayburt_Clock_Tower_%2816034875507%29.jpg/960px-Bayburt_Clock_Tower_%2816034875507%29.jpg",
  bilecik: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Bilecik.jpg/960px-Bilecik.jpg",
  bingol: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bingolcitycenter.jpg/960px-Bingolcitycenter.jpg",
  bitlis: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Bitlis_view.jpg/960px-Bitlis_view.jpg",
  bodrum: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Sunset_over_Bodrum_I.jpg/960px-Sunset_over_Bodrum_I.jpg",
  bolu: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/TR_Bolu_asv2021-10_img23_Beyaz%C4%B1t_Mosque.jpg/960px-TR_Bolu_asv2021-10_img23_Beyaz%C4%B1t_Mosque.jpg",
  burdur: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Burdur_manzara_-_panoramio.jpg/960px-Burdur_manzara_-_panoramio.jpg",
  bursa: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Teleferik%2C_Uluda%C4%9F.jpg/960px-Teleferik%2C_Uluda%C4%9F.jpg",
  canakkale: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Havadan_cnk.jpg",
  cankiri: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/General_view_of_%C3%87ank%C4%B1r%C4%B1.jpeg/960px-General_view_of_%C3%87ank%C4%B1r%C4%B1.jpeg",
  cesme: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/%C3%87e%C5%9Fme_Kalesi%2C_%C4%B0zmir%2C_2020_07.jpg/960px-%C3%87e%C5%9Fme_Kalesi%2C_%C4%B0zmir%2C_2020_07.jpg",
  corum: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/CorumMuseum1.jpg/960px-CorumMuseum1.jpg",
  denizli: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Pamukkale_Traventines%2C_Turkey.jpg/960px-Pamukkale_Traventines%2C_Turkey.jpg",
  diyarbakir: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Landscape_Dyar_bakir.jpg/960px-Landscape_Dyar_bakir.jpg",
  duzce: "https://upload.wikimedia.org/wikipedia/commons/1/19/645x344-1573480687396.jpg",
  edirne: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Selimiye_Mosque_and_The_Statue_of_Architect_Sinan_-_panoramio.jpg/960px-Selimiye_Mosque_and_The_Statue_of_Architect_Sinan_-_panoramio.jpg",
  elazig: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Elazig_Izzetpascha-Moschee.jpg/960px-Elazig_Izzetpascha-Moschee.jpg",
  erzincan: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Erzincanmerkezi.jpg/960px-Erzincanmerkezi.jpg",
  erzurum: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Erzurum_Citadel_-_Erzurum_Kalesi_01.jpg/960px-Erzurum_Citadel_-_Erzurum_Kalesi_01.jpg",
  eskisehir: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Sazova_Park_2.jpg/960px-Sazova_Park_2.jpg",
  fethiye: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Fethiye%27den_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg/960px-Fethiye%27den_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg",
  gaziantep: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Gaziantep_Archaeology_museum_Roman_Statues_Hall_4431.jpg/960px-Gaziantep_Archaeology_museum_Roman_Statues_Hall_4431.jpg",
  giresun: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Kapu_Mosque.jpg/960px-Kapu_Mosque.jpg",
  gumushane: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/G%C3%BCm%C3%BC%C5%9Fhane_Genel.JPG/960px-G%C3%BCm%C3%BC%C5%9Fhane_Genel.JPG",
  hakkari: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Hakkari.jpg/960px-Hakkari.jpg",
  hatay: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Antakya_-_2011-04-10.jpg/960px-Antakya_-_2011-04-10.jpg",
  igdir: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/I%C4%9Fd%C4%B1r_ve_A%C4%9Fr%C4%B1_Da%C4%9F%C4%B1.jpg/960px-I%C4%9Fd%C4%B1r_ve_A%C4%9Fr%C4%B1_Da%C4%9F%C4%B1.jpg",
  isparta: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/DaglardanIsparta.jpg/960px-DaglardanIsparta.jpg",
  istanbul: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Bosphorus_Bridge_%28235499411%29.jpeg/960px-Bosphorus_Bridge_%28235499411%29.jpeg",
  izmir: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/%C4%B0zmir_Clock_Tower%2C_December_2018.jpg/960px-%C4%B0zmir_Clock_Tower%2C_December_2018.jpg",
  kahramanmaras: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Kahramanmara%C5%9F_city_center.jpg/960px-Kahramanmara%C5%9F_city_center.jpg",
  kapadokya: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Cappadociasunrise.jpg/960px-Cappadociasunrise.jpg",
  nevsehir: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Cappadociasunrise.jpg/960px-Cappadociasunrise.jpg",
  karaman: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Karaman_street_scene_4727.jpg/960px-Karaman_street_scene_4727.jpg",
  kars: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Kars_collage_1.JPG",
  kas: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Ka%C5%9F'ta_gece_(Ka%C5%9F_at_night).jpg/960px-Ka%C5%9F'ta_gece_(Ka%C5%9F_at_night).jpg",
  kastamonu: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Kaleden_Cumhuriyet_Meydan%C4%B1_ve_%C3%87evresi.JPG/960px-Kaleden_Cumhuriyet_Meydan%C4%B1_ve_%C3%87evresi.JPG",
  kayseri: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Wild_horses1.jpg/960px-Wild_horses1.jpg",
  kilis: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Kilis_city_center.jpg/960px-Kilis_city_center.jpg",
  kirikkale: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/K%C4%B1r%C4%B1kkale_1_%282013%29_-_panoramio.jpg/960px-K%C4%B1r%C4%B1kkale_1_%282013%29_-_panoramio.jpg",
  kirklareli: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/K%C4%B1rklareli_5195.jpg/960px-K%C4%B1rklareli_5195.jpg",
  kirsehir: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Kircenter.jpg/960px-Kircenter.jpg",
  kocaeli: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Eskihisarkale3k.jpg",
  konya: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Konya_21_%28cropped%29.JPG/960px-Konya_21_%28cropped%29.JPG",
  kutahya: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/K%C3%BCtahya_Portesi.png/960px-K%C3%BCtahya_Portesi.png",
  malatya: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Turgut_%C3%96zal_Tabiat_Park%C4%B1_G%C3%B6l.jpg/960px-Turgut_%C3%96zal_Tabiat_Park%C4%B1_G%C3%B6l.jpg",
  manisa: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Manisa_Muradiye_Camii_Muradiye_Camii_side_to_southwest_6124.jpg/960px-Manisa_Muradiye_Camii_Muradiye_Camii_side_to_southwest_6124.jpg",
  mardin: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Mardin%2C_Mardin_Merkez-Mardin%2C_Turkey_-_panoramio_%281%29.jpg/960px-Mardin%2C_Mardin_Merkez-Mardin%2C_Turkey_-_panoramio_%281%29.jpg",
  mersin: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Mersin_Halkevi.jpg/960px-Mersin_Halkevi.jpg",
  mus: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Mush_1213.jpg/960px-Mush_1213.jpg",
  nigde: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Nigde_Kale_1228.jpg/960px-Nigde_Kale_1228.jpg",
  ordu: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Ordu%2C_Turkey.JPG/960px-Ordu%2C_Turkey.JPG",
  osmaniye: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Osmaniyenin_genel_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC.jpg/960px-Osmaniyenin_genel_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC.jpg",
  rize: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Rize%27den_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg/960px-Rize%27den_bir_g%C3%B6r%C3%BCn%C3%BCm.jpg",
  safranbolu: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Safranbolu_traditional_houses.jpg/960px-Safranbolu_traditional_houses.jpg",
  sakarya: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Hisar_Tepesi%2C_Tarakl%C4%B1.jpg/960px-Hisar_Tepesi%2C_Tarakl%C4%B1.jpg",
  samsun: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Samsun_Sahil_-_panoramio.jpg",
  sanliurfa: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Balikli_G%C3%B6l_03.jpg/960px-Balikli_G%C3%B6l_03.jpg",
  siirt: "https://upload.wikimedia.org/wikipedia/commons/3/30/City_center.jpg",
  sinop: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Sinop-Castle.jpg/960px-Sinop-Castle.jpg",
  sirnak: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/%C5%9E%C4%B1rnak_%C5%9Fehir_g%C3%B6r%C3%BCn%C3%BCm%C3%BC.jpg/960px-%C5%9E%C4%B1rnak_%C5%9Fehir_g%C3%B6r%C3%BCn%C3%BCm%C3%BC.jpg",
  sivas: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Sivas_Cumhuriyet_Meydan%C4%B1_in_2011_8145.jpg/960px-Sivas_Cumhuriyet_Meydan%C4%B1_in_2011_8145.jpg",
  tekirdag: "https://upload.wikimedia.org/wikipedia/commons/6/62/Tekirda%C4%9F_Valilik.JPG",
  tokat: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Tokat_%C5%9Fehir_panoramas%C4%B1_2012.JPG/960px-Tokat_%C5%9Fehir_panoramas%C4%B1_2012.JPG",
  trabzon: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Trabzon_Kalesi.jpeg/960px-Trabzon_Kalesi.jpeg",
  tunceli: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/D%C3%AArsim.jpg/960px-D%C3%AArsim.jpg",
  usak: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/U%C5%9Fak_Kurtulu%C5%9F_An%C4%B1t%C4%B1_ve_Atat%C3%BCrk_Heykeli.jpg/960px-U%C5%9Fak_Kurtulu%C5%9F_An%C4%B1t%C4%B1_ve_Atat%C3%BCrk_Heykeli.jpg",
  van: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ho%C5%9Fap_Kalesi_%28Van%2C_T%C3%BCrkiye%29.JPG/960px-Ho%C5%9Fap_Kalesi_%28Van%2C_T%C3%BCrkiye%29.JPG",
  yalova: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Departing_Yalova.JPG/960px-Departing_Yalova.JPG",
  yozgat: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Ormanc%C4%B1lar%C4%B1n_Emekleri_Burada_-_panoramio.jpg/960px-Ormanc%C4%B1lar%C4%B1n_Emekleri_Burada_-_panoramio.jpg",
  zonguldak: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Zonguldak_51.jpg/960px-Zonguldak_51.jpg",
};

export function getCityImage(slug: string, regionSlug?: string): string {
  const s = (slug || "").toLowerCase();
  return CITY_IMAGES[s] || REGION_IMAGES[regionSlug || ""] || REGION_IMAGES.marmara;
}
